version: '2'
services:
  peer1.example.com:
    container_name: peer1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./peer1/base.yaml:/usr/local/bin/conf/base.yaml
      
  peer2.example.com:
    container_name: peer2.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./peer2/base.yaml:/usr/local/bin/conf/base.yaml

  peer3.example.com:
    container_name: peer3.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./peer3/base.yaml:/usr/local/bin/conf/base.yaml

  peer4.example.com:
    container_name: peer4.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./peer4/base.yaml:/usr/local/bin/conf/base.yaml

  peer5.example.com:
    container_name: peer5.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./peer5/base.yaml:/usr/local/bin/conf/base.yaml