// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

/*
Package block is a generated protocol buffer package.

It is generated from these files:
	block.proto

It has these top-level messages:
	BlockHeader
	Block
*/
package block

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockHeader struct {
	Version         uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Height          uint64 `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Timestamp       uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	BlockHash       []byte `protobuf:"bytes,4,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	PreviousHash    []byte `protobuf:"bytes,5,opt,name=previousHash,proto3" json:"previousHash,omitempty"`
	WorldStateRoot  []byte `protobuf:"bytes,6,opt,name=worldStateRoot,proto3" json:"worldStateRoot,omitempty"`
	TransactionRoot []byte `protobuf:"bytes,7,opt,name=transactionRoot,proto3" json:"transactionRoot,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlockHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *BlockHeader) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *BlockHeader) GetWorldStateRoot() []byte {
	if m != nil {
		return m.WorldStateRoot
	}
	return nil
}

func (m *BlockHeader) GetTransactionRoot() []byte {
	if m != nil {
		return m.TransactionRoot
	}
	return nil
}

type Block struct {
	Header *BlockHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Txs    [][]byte     `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTxs() [][]byte {
	if m != nil {
		return m.Txs
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "block.BlockHeader")
	proto.RegisterType((*Block)(nil), "block.Block")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0xa6, 0x49, 0xc5, 0x24, 0xfc, 0x68, 0x16, 0xc8, 0x0b, 0x16, 0x51, 0x16, 0xc8,
	0x62, 0xd1, 0x05, 0xdc, 0x00, 0x09, 0xa9, 0x6b, 0x73, 0x02, 0xb7, 0xb5, 0x88, 0x45, 0x9b, 0x89,
	0xec, 0xa1, 0x70, 0x6d, 0x6e, 0x80, 0x3c, 0x14, 0x95, 0x66, 0xe7, 0xf7, 0xcd, 0x27, 0x59, 0xef,
	0x41, 0xbd, 0xde, 0xd1, 0xe6, 0x7d, 0x39, 0x46, 0x62, 0xc2, 0x52, 0x42, 0xf7, 0xad, 0xa0, 0x7e,
	0xce, 0xaf, 0x95, 0x77, 0x5b, 0x1f, 0x51, 0xc3, 0xe2, 0xe0, 0x63, 0x0a, 0x34, 0x68, 0xd5, 0x2a,
	0x73, 0x69, 0xff, 0x22, 0xde, 0x42, 0xd5, 0xfb, 0xf0, 0xd6, 0xb3, 0x9e, 0xb5, 0xca, 0xcc, 0xed,
	0x31, 0xe1, 0x1d, 0x5c, 0x70, 0xd8, 0xfb, 0xc4, 0x6e, 0x3f, 0xea, 0x42, 0x4e, 0x27, 0x90, 0xaf,
	0xf2, 0xd1, 0xca, 0xa5, 0x5e, 0xcf, 0x5b, 0x65, 0x1a, 0x7b, 0x02, 0xd8, 0x41, 0x33, 0x46, 0x7f,
	0x08, 0xf4, 0x91, 0x44, 0x28, 0x45, 0x38, 0x63, 0x78, 0x0f, 0x57, 0x9f, 0x14, 0x77, 0xdb, 0x57,
	0x76, 0xec, 0x2d, 0x11, 0xeb, 0x4a, 0xac, 0x09, 0x45, 0x03, 0xd7, 0x1c, 0xdd, 0x90, 0xdc, 0x86,
	0x03, 0x0d, 0x22, 0x2e, 0x44, 0x9c, 0xe2, 0xee, 0x05, 0x4a, 0xa9, 0x8c, 0x0f, 0xb9, 0x52, 0xae,
	0x2d, 0x5d, 0xeb, 0x47, 0x5c, 0xfe, 0x2e, 0xf4, 0x6f, 0x10, 0x7b, 0x34, 0xf0, 0x06, 0x0a, 0xfe,
	0x4a, 0x7a, 0xd6, 0x16, 0xa6, 0xb1, 0xf9, 0xb9, 0xae, 0x64, 0xc8, 0xa7, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x0d, 0x8b, 0x28, 0x98, 0x57, 0x01, 0x00, 0x00,
}
