// Code generated by protoc-gen-go. DO NOT EDIT.
// source: privateTransaction.proto

/*
Package privateTransaction is a generated protocol buffer package.

It is generated from these files:
	privateTransaction.proto

It has these top-level messages:
	Peer
	TransactionHeader
	Transaction
	Deal
*/
package privateTransaction

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 隐私交易相关方
type Peer struct {
	Id  []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Peer) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Peer) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// 交易头
type TransactionHeader struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Privacy   uint32 `protobuf:"varint,3,opt,name=privacy" json:"privacy,omitempty"`
}

func (m *TransactionHeader) Reset()                    { *m = TransactionHeader{} }
func (m *TransactionHeader) String() string            { return proto.CompactTextString(m) }
func (*TransactionHeader) ProtoMessage()               {}
func (*TransactionHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransactionHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TransactionHeader) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionHeader) GetPrivacy() uint32 {
	if m != nil {
		return m.Privacy
	}
	return 0
}

// 交易
type Transaction struct {
	Header *TransactionHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Peers  []*Peer            `protobuf:"bytes,2,rep,name=peers" json:"peers,omitempty"`
	Data   []byte             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Txid   []byte             `protobuf:"bytes,4,opt,name=txid,proto3" json:"txid,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Transaction) GetHeader() *TransactionHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Transaction) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

// 隐私交易
type Deal struct {
	SmartContract     []byte   `protobuf:"bytes,1,opt,name=smartContract,proto3" json:"smartContract,omitempty"`
	SmartContractArgs [][]byte `protobuf:"bytes,2,rep,name=smartContractArgs,proto3" json:"smartContractArgs,omitempty"`
}

func (m *Deal) Reset()                    { *m = Deal{} }
func (m *Deal) String() string            { return proto.CompactTextString(m) }
func (*Deal) ProtoMessage()               {}
func (*Deal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Deal) GetSmartContract() []byte {
	if m != nil {
		return m.SmartContract
	}
	return nil
}

func (m *Deal) GetSmartContractArgs() [][]byte {
	if m != nil {
		return m.SmartContractArgs
	}
	return nil
}

func init() {
	proto.RegisterType((*Peer)(nil), "privateTransaction.Peer")
	proto.RegisterType((*TransactionHeader)(nil), "privateTransaction.TransactionHeader")
	proto.RegisterType((*Transaction)(nil), "privateTransaction.Transaction")
	proto.RegisterType((*Deal)(nil), "privateTransaction.Deal")
}

func init() { proto.RegisterFile("privateTransaction.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0xc3, 0x40,
	0x0c, 0xc5, 0x95, 0x3f, 0x14, 0xe1, 0xa4, 0x88, 0x7a, 0xba, 0x81, 0xa1, 0x8a, 0x40, 0xca, 0x80,
	0x32, 0x94, 0x99, 0x01, 0xc1, 0xc0, 0x88, 0x4e, 0x4c, 0x6c, 0x26, 0xb1, 0xe0, 0x04, 0xf9, 0x23,
	0xc7, 0xaa, 0xe8, 0xf7, 0xe1, 0x83, 0xa2, 0x5c, 0x82, 0x68, 0x95, 0x6e, 0xf6, 0xf3, 0xfd, 0xee,
	0xbd, 0xf3, 0x81, 0xe9, 0xc4, 0x6d, 0x49, 0xf9, 0x45, 0xa8, 0xe9, 0xa9, 0x54, 0xd7, 0x36, 0x45,
	0x27, 0xad, 0xb6, 0x88, 0xf3, 0x49, 0x96, 0x43, 0xfc, 0xcc, 0x2c, 0x78, 0x0e, 0xa1, 0xab, 0x4c,
	0xb0, 0x0e, 0xf2, 0xd4, 0x86, 0xae, 0xc2, 0x0b, 0x88, 0x3e, 0x79, 0x67, 0x42, 0x2f, 0x0c, 0x65,
	0xc6, 0xb0, 0xda, 0x03, 0x9f, 0x98, 0x2a, 0x16, 0x34, 0x70, 0xba, 0x65, 0xe9, 0x5d, 0xdb, 0x78,
	0x76, 0x69, 0xff, 0x5a, 0xbc, 0x84, 0x33, 0x75, 0x35, 0xf7, 0x4a, 0x75, 0xe7, 0xaf, 0x89, 0xed,
	0xbf, 0x30, 0x70, 0x3e, 0x4c, 0xb9, 0x33, 0xd1, 0xc8, 0x4d, 0x6d, 0xf6, 0x13, 0x40, 0xb2, 0xe7,
	0x83, 0x77, 0xb0, 0xf8, 0xf0, 0x5e, 0xde, 0x20, 0xd9, 0x5c, 0x17, 0x47, 0xde, 0x37, 0x0b, 0x66,
	0x27, 0x08, 0x0b, 0x38, 0xe9, 0x98, 0xa5, 0x37, 0xe1, 0x3a, 0xca, 0x93, 0x8d, 0x39, 0x46, 0x0f,
	0x0b, 0xb0, 0xe3, 0x31, 0x44, 0x88, 0x2b, 0x52, 0xf2, 0xa9, 0x52, 0xeb, 0xeb, 0x41, 0xd3, 0x6f,
	0x57, 0x99, 0x78, 0xd4, 0x86, 0x3a, 0x7b, 0x85, 0xf8, 0x91, 0xe9, 0x0b, 0xaf, 0x60, 0xd9, 0xd7,
	0x24, 0xfa, 0xd0, 0x36, 0x2a, 0x54, 0xea, 0xb4, 0xc2, 0x43, 0x11, 0x6f, 0x60, 0x75, 0x20, 0xdc,
	0xcb, 0xfb, 0x98, 0x28, 0xb5, 0xf3, 0xc1, 0xdb, 0xc2, 0x7f, 0xd7, 0xed, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x91, 0x8e, 0xc9, 0x69, 0xca, 0x01, 0x00, 0x00,
}
