// Code generated by protoc-gen-go. DO NOT EDIT.
// source: privateTransaction.proto

/*
Package privateTransaction is a generated protocol buffer package.

It is generated from these files:
	privateTransaction.proto

It has these top-level messages:
	Header
	InterestedParty
	TxId
	TxData
	Transaction
*/
package privateTransaction

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Version   int64 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Header) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type InterestedParty struct {
	Part [][]byte `protobuf:"bytes,1,rep,name=part,proto3" json:"part,omitempty"`
}

func (m *InterestedParty) Reset()                    { *m = InterestedParty{} }
func (m *InterestedParty) String() string            { return proto.CompactTextString(m) }
func (*InterestedParty) ProtoMessage()               {}
func (*InterestedParty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InterestedParty) GetPart() [][]byte {
	if m != nil {
		return m.Part
	}
	return nil
}

type TxId struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *TxId) Reset()                    { *m = TxId{} }
func (m *TxId) String() string            { return proto.CompactTextString(m) }
func (*TxId) ProtoMessage()               {}
func (*TxId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TxId) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type TxData struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *TxData) Reset()                    { *m = TxData{} }
func (m *TxData) String() string            { return proto.CompactTextString(m) }
func (*TxData) ProtoMessage()               {}
func (*TxData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TxData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Transaction struct {
	Header     *Header          `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	NodeAndSDK *InterestedParty `protobuf:"bytes,2,opt,name=NodeAndSDK" json:"NodeAndSDK,omitempty"`
	Data       *TxData          `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Id         *TxId            `protobuf:"bytes,4,opt,name=id" json:"id,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Transaction) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Transaction) GetNodeAndSDK() *InterestedParty {
	if m != nil {
		return m.NodeAndSDK
	}
	return nil
}

func (m *Transaction) GetData() *TxData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetId() *TxId {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "privateTransaction.Header")
	proto.RegisterType((*InterestedParty)(nil), "privateTransaction.InterestedParty")
	proto.RegisterType((*TxId)(nil), "privateTransaction.TxId")
	proto.RegisterType((*TxData)(nil), "privateTransaction.TxData")
	proto.RegisterType((*Transaction)(nil), "privateTransaction.Transaction")
}

func init() { proto.RegisterFile("privateTransaction.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xe9, 0xb6, 0x54, 0x9c, 0x2e, 0x0a, 0x73, 0x90, 0x20, 0x7b, 0x58, 0x2a, 0x42, 0x4f,
	0x3d, 0xd4, 0x17, 0x50, 0xdc, 0x83, 0x45, 0x10, 0x89, 0x7d, 0x81, 0xd1, 0x04, 0xcc, 0x61, 0x93,
	0x92, 0x0e, 0xcb, 0xfa, 0xb6, 0x3e, 0x8a, 0xec, 0xb4, 0xe2, 0xa2, 0xf5, 0x36, 0xc9, 0xff, 0xff,
	0xcc, 0xff, 0x25, 0xa0, 0xfa, 0xe8, 0x76, 0xc4, 0xb6, 0x8b, 0xe4, 0x07, 0x7a, 0x63, 0x17, 0x7c,
	0xdd, 0xc7, 0xc0, 0x01, 0xf1, 0xaf, 0x52, 0xde, 0x42, 0xfe, 0x60, 0xc9, 0xd8, 0x88, 0x0a, 0x4e,
	0x76, 0x36, 0x0e, 0x2e, 0x78, 0x95, 0xac, 0x93, 0x2a, 0xd5, 0xdf, 0x47, 0x5c, 0xc1, 0x29, 0xbb,
	0xad, 0x1d, 0x98, 0xb6, 0xbd, 0x5a, 0x88, 0xf6, 0x73, 0x51, 0x5e, 0xc3, 0x79, 0xeb, 0xd9, 0x46,
	0x3b, 0xb0, 0x35, 0xcf, 0x14, 0xf9, 0x03, 0x11, 0xb2, 0x9e, 0x22, 0xab, 0x64, 0x9d, 0x56, 0x4b,
	0x2d, 0x73, 0x79, 0x01, 0x59, 0xb7, 0x6f, 0x0d, 0x9e, 0xc1, 0xc2, 0x19, 0xd9, 0xb0, 0xd4, 0x0b,
	0x67, 0xca, 0x15, 0xe4, 0xdd, 0x7e, 0x43, 0x4c, 0x87, 0x94, 0x21, 0xa6, 0x49, 0x93, 0xb9, 0xfc,
	0x4c, 0xa0, 0x38, 0xaa, 0x8b, 0x0d, 0xe4, 0xef, 0x52, 0x57, 0x5c, 0x45, 0x73, 0x59, 0xcf, 0xd0,
	0x8e, 0x40, 0x7a, 0x72, 0xe2, 0x3d, 0xc0, 0x53, 0x30, 0xf6, 0xce, 0x9b, 0x97, 0xcd, 0xa3, 0xf4,
	0x2f, 0x9a, 0xab, 0xb9, 0xdc, 0x2f, 0x0c, 0x7d, 0x14, 0xc3, 0x7a, 0x2a, 0x97, 0xfe, 0xbf, 0x76,
	0xc4, 0x18, 0x8b, 0x63, 0x25, 0x98, 0x99, 0xb8, 0xd5, 0xbc, 0xbb, 0x35, 0x87, 0x07, 0x78, 0xcd,
	0xe5, 0x73, 0x6e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xab, 0x09, 0x15, 0x13, 0xb8, 0x01, 0x00,
	0x00,
}
