// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

/*
Package transaction is a generated protocol buffer package.

It is generated from these files:
	transaction.proto

It has these top-level messages:
	TransactionHeader
	Transaction
*/
package transaction

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionHeader struct {
	Version         uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Timestamp       uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	TransactionHash []byte `protobuf:"bytes,3,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	TransactionSign []byte `protobuf:"bytes,4,opt,name=transactionSign,proto3" json:"transactionSign,omitempty"`
	BigNum          []byte `protobuf:"bytes,5,opt,name=bigNum,proto3" json:"bigNum,omitempty"`
}

func (m *TransactionHeader) Reset()                    { *m = TransactionHeader{} }
func (m *TransactionHeader) String() string            { return proto.CompactTextString(m) }
func (*TransactionHeader) ProtoMessage()               {}
func (*TransactionHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TransactionHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TransactionHeader) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionHeader) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *TransactionHeader) GetTransactionSign() []byte {
	if m != nil {
		return m.TransactionSign
	}
	return nil
}

func (m *TransactionHeader) GetBigNum() []byte {
	if m != nil {
		return m.BigNum
	}
	return nil
}

type Transaction struct {
	SmartContract     []byte             `protobuf:"bytes,1,opt,name=smartContract,proto3" json:"smartContract,omitempty"`
	Records           [][]byte           `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Header            *TransactionHeader `protobuf:"bytes,3,opt,name=header" json:"header,omitempty"`
	SmartContractArgs [][]byte           `protobuf:"bytes,4,rep,name=smartContractArgs,proto3" json:"smartContractArgs,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Transaction) GetSmartContract() []byte {
	if m != nil {
		return m.SmartContract
	}
	return nil
}

func (m *Transaction) GetRecords() [][]byte {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *Transaction) GetHeader() *TransactionHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Transaction) GetSmartContractArgs() [][]byte {
	if m != nil {
		return m.SmartContractArgs
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionHeader)(nil), "transaction.TransactionHeader")
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0x36, 0x04, 0x71, 0x49, 0x85, 0xe2, 0x01, 0xdd, 0x80, 0x50, 0x54, 0x31, 0x78,
	0x40, 0x1d, 0x40, 0x62, 0x47, 0x2c, 0x9d, 0x18, 0x0c, 0x7f, 0xc0, 0x4d, 0xad, 0xd4, 0x43, 0xec,
	0xea, 0x7c, 0xf0, 0xc7, 0x18, 0xf8, 0x7b, 0xa8, 0x56, 0xab, 0xba, 0xc9, 0xf8, 0x3e, 0x3f, 0x9d,
	0xdf, 0xbd, 0x83, 0x86, 0xc9, 0xf8, 0x68, 0x3a, 0x76, 0xc1, 0xaf, 0xf6, 0x14, 0x38, 0xc8, 0x2a,
	0x43, 0xcb, 0x3f, 0x01, 0xcd, 0xd7, 0x59, 0xaf, 0xad, 0xd9, 0x5a, 0x92, 0x08, 0xd7, 0x3f, 0x96,
	0xa2, 0x0b, 0x1e, 0x45, 0x2b, 0xd4, 0x42, 0x9f, 0xa4, 0xbc, 0x87, 0x1b, 0x76, 0x83, 0x8d, 0x6c,
	0x86, 0x3d, 0xce, 0x5a, 0xa1, 0x0a, 0x7d, 0x06, 0x52, 0xc1, 0x6d, 0x36, 0x7c, 0x6d, 0xe2, 0x0e,
	0xe7, 0xad, 0x50, 0xb5, 0x1e, 0xe3, 0x91, 0xf3, 0xd3, 0xf5, 0x1e, 0x8b, 0x89, 0xf3, 0x80, 0xe5,
	0x1d, 0x94, 0x1b, 0xd7, 0x7f, 0x7c, 0x0f, 0x78, 0x95, 0x0c, 0x47, 0xb5, 0xfc, 0x15, 0x50, 0x65,
	0xc9, 0xe5, 0x23, 0x2c, 0xe2, 0x60, 0x88, 0xdf, 0x83, 0x67, 0x32, 0x1d, 0xa7, 0xe4, 0xb5, 0xbe,
	0x84, 0x87, 0xcd, 0xc8, 0x76, 0x81, 0xb6, 0x11, 0x67, 0xed, 0x5c, 0xd5, 0xfa, 0x24, 0xe5, 0x2b,
	0x94, 0xbb, 0xb4, 0x7d, 0x8a, 0x5c, 0x3d, 0x3f, 0xac, 0xf2, 0xea, 0x26, 0x1d, 0xe9, 0xa3, 0x5b,
	0x3e, 0x41, 0x73, 0xf1, 0xc5, 0x1b, 0xf5, 0x11, 0x8b, 0x34, 0x7b, 0xfa, 0xb0, 0x29, 0xd3, 0x0d,
	0x5e, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xc4, 0x31, 0x5e, 0x98, 0x01, 0x00, 0x00,
}
