// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

/*
Package transaction is a generated protocol buffer package.

It is generated from these files:
	transaction.proto

It has these top-level messages:
	Node
	TransactionHeader
	Transaction
	Deal
*/
package transaction

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 隐私交易相关方
type Node struct {
	Id  []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Node) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Node) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// 交易头
type TransactionHeader struct {
	Version         uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Timestamp       uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Privacy         uint32 `protobuf:"varint,3,opt,name=privacy" json:"privacy,omitempty"`
	TransactionHash []byte `protobuf:"bytes,4,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	TransactionSign []byte `protobuf:"bytes,5,opt,name=transactionSign,proto3" json:"transactionSign,omitempty"`
}

func (m *TransactionHeader) Reset()                    { *m = TransactionHeader{} }
func (m *TransactionHeader) String() string            { return proto.CompactTextString(m) }
func (*TransactionHeader) ProtoMessage()               {}
func (*TransactionHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransactionHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TransactionHeader) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionHeader) GetPrivacy() uint32 {
	if m != nil {
		return m.Privacy
	}
	return 0
}

func (m *TransactionHeader) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *TransactionHeader) GetTransactionSign() []byte {
	if m != nil {
		return m.TransactionSign
	}
	return nil
}

// 交易
type Transaction struct {
	Header  *TransactionHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Nodes   []*Node            `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
	Deal    []byte             `protobuf:"bytes,3,opt,name=deal,proto3" json:"deal,omitempty"`
	Records [][]byte           `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Transaction) GetHeader() *TransactionHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Transaction) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Transaction) GetDeal() []byte {
	if m != nil {
		return m.Deal
	}
	return nil
}

func (m *Transaction) GetRecords() [][]byte {
	if m != nil {
		return m.Records
	}
	return nil
}

// 隐私交易
type Deal struct {
	SmartContract     []byte   `protobuf:"bytes,1,opt,name=smartContract,proto3" json:"smartContract,omitempty"`
	SmartContractArgs [][]byte `protobuf:"bytes,2,rep,name=smartContractArgs,proto3" json:"smartContractArgs,omitempty"`
}

func (m *Deal) Reset()                    { *m = Deal{} }
func (m *Deal) String() string            { return proto.CompactTextString(m) }
func (*Deal) ProtoMessage()               {}
func (*Deal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Deal) GetSmartContract() []byte {
	if m != nil {
		return m.SmartContract
	}
	return nil
}

func (m *Deal) GetSmartContractArgs() [][]byte {
	if m != nil {
		return m.SmartContractArgs
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "transaction.Node")
	proto.RegisterType((*TransactionHeader)(nil), "transaction.TransactionHeader")
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
	proto.RegisterType((*Deal)(nil), "transaction.Deal")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0xc4, 0x2d, 0xe2, 0x92, 0x02, 0xf1, 0xe4, 0x01, 0xa1, 0x28, 0x42, 0x22, 0x03,
	0xea, 0x50, 0x24, 0x76, 0x04, 0x43, 0x27, 0x06, 0xc3, 0xc4, 0x66, 0x62, 0xab, 0xb5, 0x20, 0x76,
	0x64, 0x5b, 0x95, 0xfa, 0x2e, 0xbc, 0x08, 0x6f, 0x57, 0xd9, 0x49, 0xd5, 0xa4, 0xd9, 0x7c, 0xdf,
	0xfd, 0xbf, 0xf5, 0xdf, 0x1d, 0xe4, 0xce, 0x30, 0x65, 0x59, 0xed, 0xa4, 0x56, 0xcb, 0xd6, 0x68,
	0xa7, 0x71, 0x3a, 0x40, 0x65, 0x05, 0xe8, 0x5d, 0x73, 0x81, 0xaf, 0x20, 0x96, 0x9c, 0x44, 0x45,
	0x54, 0x65, 0x34, 0x96, 0x1c, 0xdf, 0x40, 0xf2, 0x23, 0xf6, 0x24, 0x0e, 0xc0, 0x3f, 0xcb, 0xff,
	0x08, 0xf2, 0xcf, 0x93, 0x73, 0x2d, 0x18, 0x17, 0x06, 0x13, 0xb8, 0xd8, 0x09, 0x63, 0xa5, 0x56,
	0xc1, 0xbc, 0xa0, 0xc7, 0x12, 0xdf, 0xc2, 0xa5, 0x93, 0x8d, 0xb0, 0x8e, 0x35, 0x6d, 0xf8, 0x07,
	0xd1, 0x13, 0xf0, 0xbe, 0xd6, 0xc8, 0x1d, 0xab, 0xf7, 0x24, 0xe9, 0x7c, 0x7d, 0x89, 0x2b, 0xb8,
	0x1e, 0x04, 0x5c, 0x33, 0xbb, 0x25, 0x28, 0xa4, 0x38, 0xc7, 0x67, 0xca, 0x0f, 0xb9, 0x51, 0x64,
	0x36, 0x51, 0x7a, 0x5c, 0xfe, 0x45, 0x90, 0x0e, 0xb2, 0xe3, 0x67, 0x98, 0x6f, 0x43, 0xfe, 0x10,
	0x3a, 0x5d, 0xdd, 0x2d, 0x87, 0x6b, 0x9a, 0x4c, 0x49, 0x7b, 0x35, 0x7e, 0x80, 0x99, 0xd2, 0x5c,
	0x58, 0x12, 0x17, 0x49, 0x95, 0xae, 0xf2, 0x91, 0xcd, 0xef, 0x91, 0x76, 0x7d, 0x8c, 0x01, 0x71,
	0xc1, 0x7e, 0xc3, 0x6c, 0x19, 0x0d, 0x6f, 0x3f, 0xb2, 0x11, 0xb5, 0x36, 0xdc, 0x12, 0x54, 0x24,
	0x55, 0x46, 0x8f, 0x65, 0xf9, 0x05, 0xe8, 0xcd, 0x2b, 0xee, 0x61, 0x61, 0x1b, 0x66, 0xdc, 0xab,
	0x56, 0xce, 0xb0, 0xda, 0xf5, 0xf7, 0x18, 0x43, 0xfc, 0x08, 0xf9, 0x08, 0xbc, 0x98, 0x4d, 0x17,
	0x28, 0xa3, 0xd3, 0xc6, 0xf7, 0x3c, 0x1c, 0xfd, 0xe9, 0x10, 0x00, 0x00, 0xff, 0xff, 0x10, 0xa7,
	0x5d, 0xf0, 0x09, 0x02, 0x00, 0x00,
}
