// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaincode_shim.proto

/*
Package chaincode is a generated protocol buffer package.

It is generated from these files:
	chaincode_shim.proto

It has these top-level messages:
	ChaincodeMessage
	PutStateInfo
*/
package chaincode

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChaincodeMessage_Type int32

const (
	ChaincodeMessage_UNDEFINED           ChaincodeMessage_Type = 0
	ChaincodeMessage_REGISTER            ChaincodeMessage_Type = 1
	ChaincodeMessage_REGISTERED          ChaincodeMessage_Type = 2
	ChaincodeMessage_INIT                ChaincodeMessage_Type = 3
	ChaincodeMessage_READY               ChaincodeMessage_Type = 4
	ChaincodeMessage_TRANSACTION         ChaincodeMessage_Type = 5
	ChaincodeMessage_COMPLETED           ChaincodeMessage_Type = 6
	ChaincodeMessage_ERROR               ChaincodeMessage_Type = 7
	ChaincodeMessage_GET_STATE           ChaincodeMessage_Type = 8
	ChaincodeMessage_PUT_STATE           ChaincodeMessage_Type = 9
	ChaincodeMessage_DEL_STATE           ChaincodeMessage_Type = 10
	ChaincodeMessage_INVOKE_CHAINCODE    ChaincodeMessage_Type = 11
	ChaincodeMessage_RESPONSE            ChaincodeMessage_Type = 13
	ChaincodeMessage_GET_STATE_BY_RANGE  ChaincodeMessage_Type = 14
	ChaincodeMessage_GET_QUERY_RESULT    ChaincodeMessage_Type = 15
	ChaincodeMessage_QUERY_STATE_NEXT    ChaincodeMessage_Type = 16
	ChaincodeMessage_QUERY_STATE_CLOSE   ChaincodeMessage_Type = 17
	ChaincodeMessage_KEEPALIVE           ChaincodeMessage_Type = 18
	ChaincodeMessage_GET_HISTORY_FOR_KEY ChaincodeMessage_Type = 19
	ChaincodeMessage_GET_STATEN          ChaincodeMessage_Type = 20
	ChaincodeMessage_DEL_STATEN          ChaincodeMessage_Type = 21
	ChaincodeMessage_GET_STATE_BY_PREFIX ChaincodeMessage_Type = 22
	ChaincodeMessage_CC_PANIC            ChaincodeMessage_Type = 23
)

var ChaincodeMessage_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "REGISTER",
	2:  "REGISTERED",
	3:  "INIT",
	4:  "READY",
	5:  "TRANSACTION",
	6:  "COMPLETED",
	7:  "ERROR",
	8:  "GET_STATE",
	9:  "PUT_STATE",
	10: "DEL_STATE",
	11: "INVOKE_CHAINCODE",
	13: "RESPONSE",
	14: "GET_STATE_BY_RANGE",
	15: "GET_QUERY_RESULT",
	16: "QUERY_STATE_NEXT",
	17: "QUERY_STATE_CLOSE",
	18: "KEEPALIVE",
	19: "GET_HISTORY_FOR_KEY",
	20: "GET_STATEN",
	21: "DEL_STATEN",
	22: "GET_STATE_BY_PREFIX",
	23: "CC_PANIC",
}
var ChaincodeMessage_Type_value = map[string]int32{
	"UNDEFINED":           0,
	"REGISTER":            1,
	"REGISTERED":          2,
	"INIT":                3,
	"READY":               4,
	"TRANSACTION":         5,
	"COMPLETED":           6,
	"ERROR":               7,
	"GET_STATE":           8,
	"PUT_STATE":           9,
	"DEL_STATE":           10,
	"INVOKE_CHAINCODE":    11,
	"RESPONSE":            13,
	"GET_STATE_BY_RANGE":  14,
	"GET_QUERY_RESULT":    15,
	"QUERY_STATE_NEXT":    16,
	"QUERY_STATE_CLOSE":   17,
	"KEEPALIVE":           18,
	"GET_HISTORY_FOR_KEY": 19,
	"GET_STATEN":          20,
	"DEL_STATEN":          21,
	"GET_STATE_BY_PREFIX": 22,
	"CC_PANIC":            23,
}

func (x ChaincodeMessage_Type) String() string {
	return proto.EnumName(ChaincodeMessage_Type_name, int32(x))
}
func (ChaincodeMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

type ChaincodeMessage struct {
	Type           ChaincodeMessage_Type `protobuf:"varint,1,opt,name=type,enum=chaincode.ChaincodeMessage_Type" json:"type,omitempty"`
	Payload        []byte                `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Txid           string                `protobuf:"bytes,4,opt,name=txid" json:"txid,omitempty"`
	ChaincodeEvent *ChaincodeEvent       `protobuf:"bytes,6,opt,name=chaincode_event,json=chaincodeEvent" json:"chaincode_event,omitempty"`
}

func (m *ChaincodeMessage) Reset()                    { *m = ChaincodeMessage{} }
func (m *ChaincodeMessage) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeMessage) ProtoMessage()               {}
func (*ChaincodeMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ChaincodeMessage) GetType() ChaincodeMessage_Type {
	if m != nil {
		return m.Type
	}
	return ChaincodeMessage_UNDEFINED
}

func (m *ChaincodeMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ChaincodeMessage) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *ChaincodeMessage) GetChaincodeEvent() *ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvent
	}
	return nil
}

type PutStateInfo struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PutStateInfo) Reset()                    { *m = PutStateInfo{} }
func (m *PutStateInfo) String() string            { return proto.CompactTextString(m) }
func (*PutStateInfo) ProtoMessage()               {}
func (*PutStateInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PutStateInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutStateInfo) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*ChaincodeMessage)(nil), "chaincode.ChaincodeMessage")
	proto.RegisterType((*PutStateInfo)(nil), "chaincode.PutStateInfo")
	proto.RegisterEnum("chaincode.ChaincodeMessage_Type", ChaincodeMessage_Type_name, ChaincodeMessage_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ChaincodeSupport service

type ChaincodeSupportClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error)
}

type chaincodeSupportClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeSupportClient(cc *grpc.ClientConn) ChaincodeSupportClient {
	return &chaincodeSupportClient{cc}
}

func (c *chaincodeSupportClient) Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ChaincodeSupport_serviceDesc.Streams[0], c.cc, "/chaincode.ChaincodeSupport/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaincodeSupportRegisterClient{stream}
	return x, nil
}

type ChaincodeSupport_RegisterClient interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ClientStream
}

type chaincodeSupportRegisterClient struct {
	grpc.ClientStream
}

func (x *chaincodeSupportRegisterClient) Send(m *ChaincodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterClient) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ChaincodeSupport service

type ChaincodeSupportServer interface {
	Register(ChaincodeSupport_RegisterServer) error
}

func RegisterChaincodeSupportServer(s *grpc.Server, srv ChaincodeSupportServer) {
	s.RegisterService(&_ChaincodeSupport_serviceDesc, srv)
}

func _ChaincodeSupport_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChaincodeSupportServer).Register(&chaincodeSupportRegisterServer{stream})
}

type ChaincodeSupport_RegisterServer interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ServerStream
}

type chaincodeSupportRegisterServer struct {
	grpc.ServerStream
}

func (x *chaincodeSupportRegisterServer) Send(m *ChaincodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterServer) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChaincodeSupport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chaincode.ChaincodeSupport",
	HandlerType: (*ChaincodeSupportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _ChaincodeSupport_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chaincode_shim.proto",
}

func init() { proto.RegisterFile("chaincode_shim.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x5f, 0x53, 0xda, 0x4c,
	0x14, 0xc6, 0x8d, 0x44, 0x25, 0x47, 0xc5, 0xe3, 0x8a, 0x9a, 0xd7, 0xf7, 0x86, 0xe1, 0x8a, 0x2b,
	0xa7, 0x43, 0x3b, 0xbd, 0x8f, 0xc9, 0x01, 0xb7, 0xe0, 0x26, 0xdd, 0x2c, 0x8e, 0xdc, 0x34, 0x93,
	0xc2, 0x56, 0x99, 0x5a, 0x92, 0x81, 0xe0, 0x94, 0x2f, 0xd1, 0x2f, 0xd6, 0x2f, 0xd5, 0x59, 0x28,
	0xd1, 0x76, 0x3a, 0xde, 0x9d, 0xdf, 0x73, 0xfe, 0xe4, 0xd9, 0xcc, 0x03, 0xf5, 0xd1, 0x43, 0x3a,
	0x99, 0x8e, 0xb2, 0xb1, 0x4e, 0xe6, 0x0f, 0x93, 0x6f, 0x97, 0xf9, 0x2c, 0x2b, 0x32, 0xe6, 0x94,
	0xea, 0xc5, 0x51, 0x59, 0xae, 0x7b, 0xcd, 0x9f, 0x36, 0xa0, 0xbf, 0xd1, 0x6e, 0xf4, 0x7c, 0x9e,
	0xde, 0x6b, 0xf6, 0x0e, 0xec, 0x62, 0x99, 0x6b, 0xd7, 0x6a, 0x58, 0xad, 0x5a, 0xbb, 0x71, 0xf9,
	0xbc, 0xf4, 0xf7, 0xe8, 0xa5, 0x5a, 0xe6, 0x5a, 0xae, 0xa6, 0x99, 0x0b, 0x7b, 0x79, 0xba, 0x7c,
	0xcc, 0xd2, 0xb1, 0x5b, 0x69, 0x58, 0xad, 0x03, 0xb9, 0x41, 0xc6, 0xc0, 0x2e, 0xbe, 0x4f, 0xc6,
	0xae, 0xdd, 0xb0, 0x5a, 0x8e, 0x5c, 0xd5, 0xec, 0x0a, 0x9e, 0xbd, 0x24, 0xfa, 0x49, 0x4f, 0x0b,
	0x77, 0xb7, 0x61, 0xb5, 0xf6, 0xdb, 0xff, 0xfd, 0xeb, 0x73, 0x64, 0x06, 0x64, 0x6d, 0xf4, 0x07,
	0x37, 0x7f, 0x54, 0xc0, 0x36, 0x06, 0xd8, 0x21, 0x38, 0x03, 0x11, 0x50, 0x87, 0x0b, 0x0a, 0x70,
	0x8b, 0x1d, 0x40, 0x55, 0x52, 0x97, 0xc7, 0x8a, 0x24, 0x5a, 0xac, 0x06, 0xb0, 0x21, 0x0a, 0x70,
	0x9b, 0x55, 0xc1, 0xe6, 0x82, 0x2b, 0xac, 0x30, 0x07, 0x76, 0x24, 0x79, 0xc1, 0x10, 0x6d, 0x76,
	0x04, 0xfb, 0x4a, 0x7a, 0x22, 0xf6, 0x7c, 0xc5, 0x43, 0x81, 0x3b, 0xe6, 0xa4, 0x1f, 0xde, 0x44,
	0x7d, 0x52, 0x14, 0xe0, 0xae, 0x19, 0x25, 0x29, 0x43, 0x89, 0x7b, 0xa6, 0xd3, 0x25, 0x95, 0xc4,
	0xca, 0x53, 0x84, 0x55, 0x83, 0xd1, 0x60, 0x83, 0x8e, 0xc1, 0x80, 0xfa, 0xbf, 0x11, 0x58, 0x1d,
	0x90, 0x8b, 0xdb, 0xb0, 0x47, 0x89, 0x7f, 0xed, 0x71, 0xe1, 0x87, 0x01, 0xe1, 0xfe, 0xda, 0x60,
	0x1c, 0x85, 0x22, 0x26, 0x3c, 0x64, 0x67, 0xc0, 0xca, 0x83, 0xc9, 0xd5, 0x30, 0x91, 0x9e, 0xe8,
	0x12, 0xd6, 0xcc, 0xae, 0xd1, 0x3f, 0x0e, 0x48, 0x0e, 0x13, 0x49, 0xf1, 0xa0, 0xaf, 0xf0, 0xc8,
	0xa8, 0x6b, 0x65, 0x3d, 0x2f, 0xe8, 0x4e, 0x21, 0xb2, 0x53, 0x38, 0x7e, 0xa9, 0xfa, 0xfd, 0x30,
	0x26, 0x3c, 0x36, 0x6e, 0x7a, 0x44, 0x91, 0xd7, 0xe7, 0xb7, 0x84, 0x8c, 0x9d, 0xc3, 0x89, 0xb9,
	0x78, 0xcd, 0x63, 0x15, 0xca, 0x61, 0xd2, 0x09, 0x65, 0xd2, 0xa3, 0x21, 0x9e, 0x98, 0x7f, 0x54,
	0x5a, 0x10, 0x58, 0x37, 0x5c, 0xbe, 0x42, 0xe0, 0xe9, 0x66, 0xb1, 0xb4, 0x18, 0x49, 0xea, 0xf0,
	0x3b, 0x3c, 0x33, 0x2f, 0xf1, 0xfd, 0x24, 0xf2, 0x04, 0xf7, 0xf1, 0xbc, 0xf9, 0x1e, 0x0e, 0xa2,
	0x45, 0x11, 0x17, 0x69, 0xa1, 0xf9, 0xf4, 0x4b, 0xc6, 0x10, 0x2a, 0x5f, 0xf5, 0x72, 0x95, 0x23,
	0x47, 0x9a, 0x92, 0xd5, 0x61, 0xe7, 0x29, 0x7d, 0x5c, 0x68, 0x77, 0x7b, 0x15, 0x91, 0x35, 0xb4,
	0x3f, 0xbd, 0x08, 0x61, 0xbc, 0xc8, 0xf3, 0x6c, 0x56, 0xb0, 0x0f, 0x50, 0x95, 0xfa, 0x7e, 0x32,
	0x2f, 0xf4, 0x8c, 0xfd, 0xff, 0x4a, 0x04, 0x2f, 0x5e, 0x6b, 0x36, 0xb7, 0x5a, 0xd6, 0x1b, 0xeb,
	0xf3, 0xee, 0x2a, 0xec, 0x6f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x69, 0xfb, 0x49, 0x20,
	0x03, 0x00, 0x00,
}
