PackTime: 1000
Admin: "4X7QusyWrQEiKHJmLqkBQNM5T8GMbbGYsksShNDiGrPRsVA3RHwWLehi7R9UQQMn3rv9rn7W2B7pSBPviUygAeCc"
Log:
    Level: "Info"
    LogDir: ""
    LogFile: ""
    RaftLevel: "Debug"
Rpc:
    Port: 8000
    Timeout: 50
    UseTLS: false
    TLSCaPath: "./crypt/ca.pem"
    TLSKeyPath: "./crypt/key.pem"
    TLSCertPath: "./crypt/cert.pem"
    TLSServerName: "test.example.com"
Node:
    NodeCertPath: "./cert/nodeCert.pem"
    NodeKeyPath: "./cert/nodeKey.pem"
    RootCertPath: "./cert/root.pem"
StorePath:
    Path: "peer.db"
    WorldStatePath: "worldstate.db"
Crypt:
    KeyTyp: "sm2"
    HashTyp: "sm3"
    KeyPath: "./crypt/key.pem"
Docker:
    Ip: "0.0.0.0"
    Port: "7051"
    Loglevel: "ERROR"
    Endpoint: unix:///var/run/docker.sock
    BaseImage: "tjfoc/tjfoc-ccenv"
    Version: "1.0.1"
    Enable: true
Chaincode:
    Timeout: 30s
Block:
     PackTimeout: 1000
Raft:
    HeartBeat: 500
    VoteTimeout: 5000
Self:
    Id: "101"
    Addr: "10.1.4.101:50000"
Members:
    Port: 50000
    P2P:
        Cycle: 10000
    Peers:
        - Id: "101"
          Addr: "10.1.4.101:50000"
        - Id: "152"
          Addr: "10.1.4.152:50000"
        # - Id: "159"
        #   Addr: "10.1.3.159:50000"
